global class WrapperVenta {
    
    public String Nombre{get;set;}
    public String Direccion{get;set;}
    public String NombreOportunidad{get;set;}
    public String Telefono{get;set;}
    public Date FechaSorteo{get;set;}
    public String Status{get;set;}
}
    /*JSON
{
"venta":{
  "Nombre":"Examen: Cuenta de Sorteo",
  "Direccion":"Lanin 987",
  "NombreOportunidad":"BL-12345",
  "Telefono":"2995512660",
  "FechaSorteo":"2021-8-27",
  "Status": "Prospecting"}
 }*/