global class WrapperSale {
    
    
     global string nombre{get;set;}
      global string direccion{get;set;}
      global string telefono{get;set;}
      global string nombreOportunidad{get;set;}
      global date fechaSorteo{get;set;}
      global string status{get;set;}
    
    
    
}
    
    





/*

{

"cliente":{
  "nombre":"Evelyn Zottola",
  "direccion":"La pinta 3513",
   "telefono":"2995512660",    
   "nombreOportunidad":"BL-Numero",  
    "fechaSorteo":"2021-8-27",
    "status": "Closed Won"
 }
}
*/

