global class wrapperBoleto {
    global string Name{get;set;}
    global string Address{get;set;}
    global string Phone{get;set;}
       global string NombreBL{get;set;}
       global Date DateLottery{get;set;}
       global String Stage{get; set;}
    
    
           global NumeroGandor NumeroGandor; 
        global class NumeroGandor {
        global Date Fecha {get;set;}
        global String folio {get;set;}
    }
}